# Generated by Django 4.2 on 2023-05-02 21:53

from django.db import migrations, models
import django.db.models.deletion
import integrationIfood.models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0007_markets_id_ifood_markets_integration_ifood_and_more'),
        ('integrationIfood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationconfig',
            name='integration_base_url',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='integration_environment',
            field=models.CharField(default='DEV', max_length=20, verbose_name=integrationIfood.models.IntegrationEnvirionment),
        ),
        migrations.CreateModel(
            name='IntegrarionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='markets.markets')),
            ],
        ),
    ]
