# Generated by Django 4.2 on 2023-05-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrationIfood', '0002_integrationconfig_integration_base_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconfig',
            name='integration_base_url',
            field=models.URLField(default=None, max_length=120),
        ),
    ]
