# Generated by Django 4.2 on 2023-05-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrationIfood', '0003_alter_integrationconfig_integration_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconfig',
            name='integration_environment',
            field=models.CharField(choices=[('DEV', 'DEVELOPMENT'), ('HML', 'HOMOLOGATION'), ('PRD', 'PRODUCTION')], max_length=3),
        ),
    ]
