# Generated by Django 4.1.7 on 2023-04-25 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIntegrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Markets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name='id:')),
                ('name', models.CharField(max_length=200, verbose_name='razao social:')),
                ('common_name', models.CharField(max_length=60, verbose_name='nome fantasia:')),
                ('document_number', models.BigIntegerField(max_length=14, verbose_name='cnpj:')),
            ],
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name='id:')),
                ('adrress', models.CharField(max_length=100, verbose_name='endreço:')),
                ('address_number', models.IntegerField(max_length=10, verbose_name='numero:')),
                ('address_details', models.CharField(max_length=50, verbose_name='complemento:')),
                ('address_neighborhood', models.CharField(max_length=50, verbose_name='bairro:')),
                ('address_city', models.CharField(max_length=60, verbose_name='municipio')),
                ('address_state', models.CharField(max_length=2, verbose_name='estado:')),
                ('address_country', models.CharField(max_length=50, verbose_name='pais:')),
                ('address_postal_code', models.IntegerField(max_length=8, verbose_name='codigo postal:')),
                ('creation_date', models.DateTimeField(verbose_name='data de cadastro:')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.markets')),
            ],
        ),
    ]
