# Generated by Django 4.1.7 on 2023-04-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name='id:')),
                ('adrress', models.CharField(max_length=100, verbose_name='endreço:')),
                ('address_number', models.IntegerField(max_length=10, verbose_name='numero:')),
                ('address_details', models.CharField(max_length=50, verbose_name='complemento:')),
                ('address_neighborhood', models.CharField(max_length=50, verbose_name='bairro:')),
                ('address_city', models.CharField(max_length=60, verbose_name='municipio')),
                ('address_state', models.CharField(max_length=2, verbose_name='estado:')),
                ('address_country', models.CharField(max_length=50, verbose_name='pais:')),
                ('address_postal_code', models.IntegerField(max_length=8, verbose_name='codigo postal:')),
                ('creation_date', models.DateTimeField(verbose_name='data de cadastro:')),
            ],
        ),
        migrations.AddField(
            model_name='marketintegrations',
            name='access_key',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='marketintegrations',
            name='integration_host',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketintegrations',
            name='secre_access_key',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Addresses',
        ),
    ]
