# Generated by Django 4.1.7 on 2023-04-25 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_marketaddress_marketintegrations_access_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketaddress',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='markets.markets'),
        ),
        migrations.AddField(
            model_name='marketintegrations',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='markets.markets'),
        ),
    ]
