# Generated by Django 4.1.7 on 2023-04-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_marketaddress_market_marketintegrations_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketaddress',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='markets',
            name='uuid',
        ),
    ]
