# Generated by Django 4.1.7 on 2023-04-25 20:53

from django.db import migrations, models
import markets.models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_remove_marketaddress_uuid_remove_markets_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketintegrations',
            old_name='secre_access_key',
            new_name='secret_access_key',
        ),
        migrations.AddField(
            model_name='markets',
            name='market_type',
            field=models.CharField(max_length=20, null=True, verbose_name=markets.models.MarketType),
        ),
    ]
