# Generated by Django 4.2 on 2023-04-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_rename_secre_access_key_marketintegrations_secret_access_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='markets',
            name='creation_date',
            field=models.DateTimeField(null=True, verbose_name='data criacao'),
        ),
    ]
