# Generated by Django 4.2 on 2023-04-30 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_markets_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='markets',
            name='id_ifood',
            field=models.UUIDField(default=12345, verbose_name='id da loja ifood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='markets',
            name='integration_ifood',
            field=models.BooleanField(default=False, verbose_name='integra com ifood'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketintegrations',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.markets'),
        ),
    ]
